"""
export_to_c.py
将训练好的模型（GA 或 PPO）导出为 STM32 C 头文件 model_weights.h
自动检测文件路径，兼容两种训练方式
"""
import pickle
import numpy as np
import os

# 优先使用 PPO 模型，若不存在则用 GA 模型
# 优先使用 PPO v5 模型
PPO_V5_PATH = "E:\\Test_FIre\\best_model_v5_branched.pkl"
PPO_PATH = "E:\\Test_FIre\\best_model_ppo_dynamic_attacker.pkl"
GA_PATH  = "E:\\Test_FIre\\best_model.pkl"
OUT_PATH = "E:\\Test_FIre\\model_weights.h"

if os.path.exists(PPO_V5_PATH):
    MODEL_PATH = PPO_V5_PATH
    src = "PPO_V5_BRANCHED"
elif os.path.exists(PPO_PATH):
    MODEL_PATH = PPO_PATH
    src = "PPO"
elif os.path.exists(GA_PATH):
    MODEL_PATH = GA_PATH
    src = "GA"
else:
    raise FileNotFoundError("未找到模型文件，请先完成训练。")

with open(MODEL_PATH, "rb") as f:
    weights = pickle.load(f)

def to_c_array(name, arr):
    flat = arr.flatten()
    vals = ", ".join(f"{v:.6f}f" for v in flat)
    s = arr.shape
    if len(s) == 1:
        return f"const float {name}[{s[0]}] = {{{vals}}};\n"
    return f"const float {name}[{s[0]}][{s[1]}] = {{{vals}}};\n"

if src == "PPO_V5_BRANCHED":
    W1, B1, W_Off, B_Off, W_Tac, B_Tac, W_mv, B_mv, W_rt, B_rt, W_fire, B_fire = weights
    arch = f"16->Shared(64)->[Off(48),Tac(48)]->[rt(3)/fire(1), mv(3)]"
    total = sum(x.size for x in weights)
    with open(OUT_PATH, "w") as f:
        f.write("#pragma once\n\n")
        f.write(f"// Auto-generated by export_to_c.py  (source: {src})\n")
        f.write(f"// Architecture : {arch}\n")
        f.write(f"// Parameters   : {total}  ({total*4} bytes = {total*4/1024:.1f} KB Flash)\n\n")
        f.write(to_c_array("W_Shared", W1))
        f.write(to_c_array("B_Shared", B1))
        f.write(to_c_array("W_Offense", W_Off))
        f.write(to_c_array("B_Offense", B_Off))
        f.write(to_c_array("W_Tactical", W_Tac))
        f.write(to_c_array("B_Tactical", B_Tac))
        f.write(to_c_array("W_Mv_Head", W_mv))
        f.write(to_c_array("B_Mv_Head", B_mv))
        f.write(to_c_array("W_Rt_Head", W_rt))
        f.write(to_c_array("B_Rt_Head", B_rt))
        f.write(to_c_array("W_Fire_Head", W_fire))
        f.write(to_c_array("B_Fire_Head", B_fire))
else:
    # 兼容旧版本
    W1, B1, W2, B2, W3, B3, W4, B4 = weights
    arch = f"{W1.shape[0]}-{W1.shape[1]}-{W2.shape[1]}-{W3.shape[1]}-{W4.shape[1]}"
    total = sum(x.size for x in weights)
    
    with open(OUT_PATH, "w") as f:
        f.write("#pragma once\n\n")
        f.write(f"// Auto-generated by export_to_c.py  (source: {src})\n")
        f.write(f"// Architecture : {arch}\n")
        f.write(f"// Parameters   : {total}  ({total*4} bytes = {total*4/1024:.1f} KB Flash)\n\n")
        f.write(to_c_array("W1", W1))
        f.write(to_c_array("B1", B1))
        f.write(to_c_array("W2", W2))
        f.write(to_c_array("B2", B2))
        f.write(to_c_array("W3", W3))
        f.write(to_c_array("B3", B3))
        f.write(to_c_array("W4", W4))
        f.write(to_c_array("B4", B4))

print(f"[{src}] 导出成功: {arch} -> {OUT_PATH}")
print(f"  参数量: {total}   Flash: {total*4}B = {total*4/1024:.1f}KB")
